Add self-test for Trivy pre-install
Tests that if Trivy is pre-installed and skip-trivy-install: true the
scan action still works correctly

diff --git a/.github/workflows/self-tests.yml b/.github/workflows/self-tests.yml
--- a/.github/workflows/self-tests.yml
+++ b/.github/workflows/self-tests.yml
@@ -96,3 +96,50 @@ jobs:
         with:
           name: maven-trivy-sbom-scan-reports-${{ github.job }}
           path: /tmp
+
+  pre-installed:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Setup Java and Maven
+        uses: actions/setup-java@v4
+        with:
+          distribution: temurin
+          java-version: 21
+          cache: maven
+
+      - name: Maven Build
+        run: |
+          mvn --batch-mode clean install
+
+      - name: Pre-install Trivy
+        uses: jaxxstorm/action-install-gh-release@v1.12.0
+        with:
+          repo: aquasecurity/trivy
+          arch: 64bit
+          tag: v0.52.0
+          cache: enable
+
+      - name: Maven Trivy Scan
+        id: trivy
+        continue-on-error: true
+        uses: Telicent-io/maven-trivy-scan-action@v1
+        with:
+          pattern: "*-bom.json"
+          directory: src/it/known-vulnerability
+          skip-trivy-install: true
+
+      - name: Ensure Trivy Scan Step Failed
+        if: ${{ steps.trivy.outcome == 'success' }}
+        run: |
+          echo "Trivy Scanning Step DID NOT fail as expected"
+          exit 1
+
+      - name: Ensure Scan Reports were uploaded
+        if: always()
+        uses: actions/download-artifact@v4
+        with:
+          name: maven-trivy-sbom-scan-reports-${{ github.job }}
+          path: /tmp
