Self-test for case of no valid POM

diff --git a/.github/workflows/self-tests.yml b/.github/workflows/self-tests.yml
--- a/.github/workflows/self-tests.yml
+++ b/.github/workflows/self-tests.yml
@@ -128,13 +128,12 @@ jobs:
         uses: Telicent-io/maven-trivy-scan-action@v1
         with:
           pattern: "*-bom.json"
-          directory: src/it/known-vulnerability
           skip-trivy-install: true
 
-      - name: Ensure Trivy Scan Step Failed
-        if: ${{ steps.trivy.outcome == 'success' }}
+      - name: Ensure Trivy Scan Step Succeeded
+        if: ${{ steps.trivy.outcome != 'success' }}
         run: |
-          echo "Trivy Scanning Step DID NOT fail as expected"
+          echo "Trivy Scanning Step DID NOT succeed as expected"
           exit 1
 
       - name: Ensure Scan Reports were uploaded
@@ -143,3 +142,19 @@ jobs:
         with:
           name: maven-trivy-sbom-scan-reports-${{ github.job }}
           path: /tmp
+
+  no-pom:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Maven Trivy Scan
+        id: trivy
+        continue-on-error: true
+        uses: Telicent-io/maven-trivy-scan-action@v1
+        with:
+          directory: .github/
+
+      - name: Ensure Trivy Scan Step Failed
+        if: ${{ steps.trivy.outcome == 'success' }}
+        run: |
+          echo "Trivy Scanning Step DID NOT fail as expected"
+          exit 1
