Add self-test around Maven with no SBOMs generated

diff --git a/.github/workflows/self-tests.yml b/.github/workflows/self-tests.yml
--- a/.github/workflows/self-tests.yml
+++ b/.github/workflows/self-tests.yml
@@ -158,3 +158,19 @@ jobs:
         run: |
           echo "Trivy Scanning Step DID NOT fail as expected"
           exit 1
+
+  no-sboms:
+    runs-on: ubuntu-latest
+    steps:
+      # No Maven Build Steps so no SBOMs will be present
+
+      - name: Maven Trivy Scan
+        id: trivy
+        continue-on-error: true
+        uses: Telicent-io/maven-trivy-scan-action@v1
+
+      - name: Ensure Trivy Scan Step Failed
+        if: ${{ steps.trivy.outcome == 'success' }}
+        run: |
+          echo "Trivy Scanning Step DID NOT fail as expected"
+          exit 1
